### ISSUE TITLE
JSX formatting

### ISSUE THREAD

**Issue by alexandrebodin** [grommet/jsx-to-string#24]
Currently the formatting will output props in the following fashion:

```JSX
<Component name='name'
  value={1}
  isOpen={true} />
```

Most standards (e.g prettier) would expect something more like this:

```JSX
<Component
  isOpen={true}
  value={1}
  name='name'
/>
```

I would suggest adding a formatting option for different formatting styles and using some defaults matching most standards. 

What's your opinion ? Should I work on a PR ?

**Comment by alansouzati** [comment]
Hey sorry for taking such a long time to reply to this. I actually like the idea of adding a formatter. Can you work on a PR for this?
