### ISSUE TITLE
"item is not defined" with array of objects containing function

### ISSUE THREAD

**Issue by annesof** [grommet/jsx-to-string#26]
Hi, 
I try to transform an object like this 
`      const actions = [
            { component:<i className="fa fa-pencil" id="topTooltip"/>, event: () => alert('This is the first action') },
            { component: <Button>Action 2</Button>, event: () => alert('This is the second action') },]`

So I see that in the function stringifyObject, there is a bug in the last `else if`. 
Indeed, item is never defined so the function is in error. Could you fixed the problem? Thanks in advance.

**Comment by amiryonatan** [comment]
Fixed 1.3.1 @alansouzati you can close this issue
