### ISSUE TITLE
alternate boolean syntax

### ISSUE THREAD

**Issue by afraser** [grommet/jsx-to-string#29]
I'd love to see support for omitting boolean values:

eg:
```
<button />
<button disabled />
```
instead of
```
<button disabled={false} />
<button disabled={true} />
```
(respectively)

**Comment by alansouzati** [comment]
great request. are you up for a pull request on that feature?
I can this an option, maybe `shortBooleanProp: true`.

**Comment by lucmerceron** [comment]
Hello guys,

I could do that if @afraser did not begin to work on it :)

**Comment by afraser** [comment]
I have not. Go for it @lucmerceron!
